# Generated by Django 5.1.1 on 2024-09-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_user_id_post_comment_postinteraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
